generator:
  class: sfDoctrineGenerator
  param:
    model_class:            aBlogPost
    column:                 slug
    theme:                  aBlogAdmin
    non_verbose_templates:  true
    with_show:              false
    singular:               ~
    plural:                 ~
    route_prefix:           a_blog_admin
    with_doctrine_route:    1
    
    config:
      fields:
        author_id:  { label: created by }
        _editors_list: { label: edited by }
        _categories_list: { label: categories }
        tags_list: { label: tagged }       
      
      list:
        title:    "Blog Post Admin"
        display:  [ _title, _author_id, _editors_list, _tags_list, _categories_list, status, published_at ]
        fields:
          author_id:
            label:  Author
          editors_list:
            label:  Editors
            type:   ManyKey
          tags_list:
            label:  Tags
          categories_list:
            label:  Categories
            type:   ManyKey
          
                
      filter:
        fields:   [ author_id, editors_list, categories_list, status, _tags_list ]
        display:  [ author_id, editors_list, categories_list, status, _tags_list ]