generator:
  class: sfDoctrineGenerator
  param:
    model_class:           aBlogPost
    column: slug
    theme:                 aAdminAlt
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          a_blog_admin
    with_doctrine_route:   1
    
    config:
          
      list:
        title:    "Blog Post Admin"
        display:  [ _title, _author, _editors, _tags, _categories, status, published_at ]
        object_actions: []
        actions: ~
                
      filter:
        fields:  [ author_id, editors_list, categories_list, status,  published_at, ~tagList ]
        display: [ author_id, editors_list, categories_list, status,  published_at, ~tagList ]
        
      form:
        fields:  [ author_id ]
        display: [ author_id ]
      
      fields:
        author_id:  { label: created by }
        editors_list: { label: edited by }
        categories_list: { label: categories }
        tags_list: { label: tagged }        
        
      edit:
        fields: [ author_id ]
