all:        
  aBlog:
    templates: 
      singleColumnTemplate: Single Column
      twoColumnTemplate: Two Column
      bannerTemplate: Banner Template
    comments: false
    # add_this: punkave     # Username for AddThis -- http://addthis.com
  aEvent:
    templates:
      singleColumnTemplate: Single Column
