all:
  aComment:
    aBlogPost:
      threaded: false
      max_depth: 0
      layout:
        title: optional
        
  aBlog:
    templates: 
      singleColumnTemplate: Single Column
      twoColumnTemplate: Two Column