all:        
  aBlog:
    templates: 
      singleColumnTemplate: Single Column
      twoColumnTemplate: Two Column
      # bannerTemplate: Banner Template # Dan, I wanna make a banner template bundled with the plugin
    comments: false
  aEvent:
    templates:
      singleColumnTemplate: Single Column
