#################
# aBlog routes #
#################

a_blog_post:
  url:     /:year/:month/:day/:slug
  param:   { module: aBlog, action: show }
  options: { model: aBlogPost, type: object }
  requirements: { year: '\d{4}', month: '\d|\d{2}', day: '\d|\d{2}' }
  class:   aDoctrineRoute

a_blog_cat_tag_year_month_day:
  url:   /:cat/tag/:tag/:year/:month/:day
  param: { module: aBlog, action: index }
  requirements: { year: '\d{4}', month: '\d|\d{2}', day: '\d|\d{2}' }
  class: aRoute

a_blog_cat_tag_year_month:
  url:   /:cat/tag/:tag/:year/:month
  param: { module: aBlog, action: index }
  requirements: { year: '\d{4}', month: '\d|\d{2}' }
  options: 
    filters: [ filterByYMD, filterByCategory, filterByTag ] 
  class: aRoute

a_blog_cat_tag_year:
  url:   /:cat/tag/:tag/:year
  param: { module: aBlog, action: index }
  requirements: { year: '\d{4}' }
  options: 
    filters: [ filterByYMD, filterByCategory ] 
  class: aRoute

a_blog_tag_year_month_day:
  url:   /tag/:tag/:year/:month/:day
  param: { module: aBlog, action: index }
  options: 
    filters: [ filterByYMD, filterByCategory ] 
  requirements: { year: '\d{4}', month: '\d|\d{2}', day: '\d|\d{2}' }
  class: aRoute

a_blog_tag_year_month:
  url:   /tag/:tag/:year/:month
  param: { module: aBlog, action: index }
  options: 
    filters: [ filterByYMD, filterByCategory ] 
  requirements: { year: '\d{4}', month: '\d|\d{2}' }
  class: aRoute

a_blog_tag_year:
  url:   /tag/:tag/:year
  param: { module: aBlog, action: index }
  options: 
    filters: [ filterByYMD ] 
  requirements: { year: '\d{4}' }
  class: aRoute

a_blog_cat_year_month_day:
  url:   /:cat/:year/:month/:day
  param: { module: aBlog, action: index }
  options: 
    filters: [ filterByYMD, filterByCategory ] 
  requirements: { year: '\d{4}', month: '\d|\d{2}', day: '\d|\d{2}' }
  class: aRoute

a_blog_cat_year_month:
  url:   /:cat/:year/:month
  param: { module: aBlog, action: index }
  options: 
    filters: [ filterByYMD, filterByCategory ] 
  requirements: { year: '\d{4}', month: '\d|\d{2}' }
  class: aRoute

a_blog_cat_year:
  url:   /:cat/:year
  param: { module: aBlog, action: index }
  options: 
    filters: [ filterByYMD, filterByCategory ] 
  requirements: { year: '\d{4}' }
  class: aRoute
  
a_blog_year_month_day:
  url:   /:year/:month/:day
  options: 
    filters: [ filterByYMD ] 
  param: { module: aBlog, action: index }
  requirements: { year: '\d{4}', month: '\d|\d{2}', day: '\d|\d{2}' }
  class: aRoute

a_blog_year_month:
  url:   /:year/:month
  param: { module: aBlog, action: index }
  options: 
    filters: [ filterByYMD ]
  requirements: { year: '\d{4}', month: '\d|\d{2}' }
  class: aRoute

a_blog_year:
  url:   /:year
  options: 
    filters: [ filterByYMD ]
  param: { module: aBlog, action: index }
  requirements: { year: '\d{4}' }
  class: aRoute

a_blog_cat_tag:
  url:   /:cat/tag/:tag
  param: { module: aBlog, action: index }
  options: 
    filters: [ filterByCategory ] 
  class: aRoute

a_blog_tag:
  url:   /tag/:tag
  param: { module: aBlog, action: index }
  options: 
    filters: [ filterByTag ] 
  class: aRoute

a_blog_cat:
  url:   /:cat
  options: 
    filters: [ filterByCategory ] 
  param: { module: aBlog, action: index }
  class: aRoute

a_blog:
  url:   
  param: { module: aBlog, action: index }
  class: aRoute

a_blog_today:
  url:   
  param: { module: aBlog, action: today }
  class: aRoute
 
#################
# aEvent routes #
#################

a_event_post:
  url:     /:year/:month/:day/:slug
  param:   { module: aEvent, action: show }
  options: { model: aEvent, type: object }
  requirements: { year: '\d{4}', month: '\d|\d{2}', day: '\d|\d{2}' }
  class:   aDoctrineRoute

a_event_cat_tag_year_month_day:
  url:   /:cat/tag/:tag/:year/:month/:day
  param: { module: aEvent, action: index }
  requirements: { year: '\d{4}', month: '\d|\d{2}', day: '\d|\d{2}' }
  class: aRoute

a_event_cat_tag_year_month:
  url:   /:cat/tag/:tag/:year/:month
  param: { module: aEvent, action: index }
  requirements: { year: '\d{4}', month: '\d|\d{2}' }
  options: 
    filters: [ filterByYMD, filterByCategory, filterByTag ] 
  class: aRoute

a_event_cat_tag_year:
  url:   /:cat/tag/:tag/:year
  param: { module: aEvent, action: index }
  requirements: { year: '\d{4}' }
  options: 
    filters: [ filterByYMD, filterByCategory ] 
  class: aRoute

a_event_tag_year_month_day:
  url:   /tag/:tag/:year/:month/:day
  param: { module: aEvent, action: index }
  options: 
    filters: [ filterByYMD, filterByCategory ] 
  requirements: { year: '\d{4}', month: '\d|\d{2}', day: '\d|\d{2}' }
  class: aRoute

a_event_tag_year_month:
  url:   /tag/:tag/:year/:month
  param: { module: aEvent, action: index }
  options: 
    filters: [ filterByYMD, filterByCategory ] 
  requirements: { year: '\d{4}', month: '\d|\d{2}' }
  class: aRoute

a_event_tag_year:
  url:   /tag/:tag/:year
  param: { module: aEvent, action: index }
  options: 
    filters: [ filterByYMD ] 
  requirements: { year: '\d{4}' }
  class: aRoute

a_event_cat_year_month_day:
  url:   /:cat/:year/:month/:day
  param: { module: aEvent, action: index }
  options: 
    filters: [ filterByYMD, filterByCategory ] 
  requirements: { year: '\d{4}', month: '\d|\d{2}', day: '\d|\d{2}' }
  class: aRoute

a_event_cat_year_month:
  url:   /:cat/:year/:month
  param: { module: aEvent, action: index }
  options: 
    filters: [ filterByYMD, filterByCategory ] 
  requirements: { year: '\d{4}', month: '\d|\d{2}' }
  class: aRoute

a_event_cat_year:
  url:   /:cat/:year
  param: { module: aEvent, action: index }
  options: 
    filters: [ filterByYMD, filterByCategory ] 
  requirements: { year: '\d{4}' }
  class: aRoute
  
a_event_year_month_day:
  url:   /:year/:month/:day
  options: 
    filters: [ filterByYMD ] 
  param: { module: aEvent, action: index }
  requirements: { year: '\d{4}', month: '\d|\d{2}', day: '\d|\d{2}' }
  class: aRoute

a_event_year_month:
  url:   /:year/:month
  param: { module: aEvent, action: index }
  options: 
    filters: [ filterByYMD ]
  requirements: { year: '\d{4}', month: '\d|\d{2}' }
  class: aRoute

a_event_year:
  url:   /:year
  options: 
    filters: [ filterByYMD ]
  param: { module: aEvent, action: index }
  requirements: { year: '\d{4}' }
  class: aRoute

a_event_cat_tag:
  url:   /:cat/tag/:tag
  param: { module: aEvent, action: index }
  options: 
    filters: [ filterByCategory ] 
  class: aRoute

a_event_tag:
  url:   /tag/:tag
  param: { module: aEvent, action: index }
  options: 
    filters: [ filterByTag ] 
  class: aRoute

a_event_cat:
  url:   /:cat
  options: 
    filters: [ filterByCategory ] 
  param: { module: aEvent, action: index }
  class: aRoute

a_event:
  url:   
  param: { module: aEvent, action: index }
  class: aRoute

a_event_today:
  url:   
  param: { module: aEvent, action: today }
  class: aRoute 
  
  
################
# blog admin routes #
################

a_blog_admin:
  class: sfDoctrineRouteCollection
  options:
    model:               aBlogPost
    module:              aBlogAdmin
    prefix_path:         admin/blog
    column:              slug
    with_wildcard_routes: false
      
a_blog_admin_removeFilter:
  url:   /admin/aBlogAdmin/remove_filter/:name/:value
  param: { module: aBlogAdmin, action: removeFilter }
  class: sfRoute
  
a_blog_admin_addFilter:
  url:   /admin/aBlogAdmin/add_filter/:name/:value
  param: { module: aBlogAdmin, action: addFilter }
  class: sfRoute
  
a_blog_admin_autocomplete:
  url:   /admin/aBlogAdmin/autocomplete
  param: { module: aBlogAdmin, action: autocomplete }
  class: sfRoute
  
a_blog_admin_editCategories:
  url:   /admin/aBlogAdmin/editCategories
  param: { module: aBlogAdmin, action: editCategories }
  class: sfRoute  
      
a_blog_category_admin:
  class: sfDoctrineRouteCollection
  options:
    model:               aBlogCategory
    module:              aBlogCategoryAdmin
    prefix_path:         admin/blog_categories
    column:              id
    with_wildcard_routes: true
    collection_actions:
      addFilter: [GET, POST]
      removeFilter: [GET, POST]
      
      
######################
# event admin routes #
######################

a_event_admin:
  class: sfDoctrineRouteCollection
  options:
    model:               aEvent
    module:              aEventAdmin
    prefix_path:         admin/event
    column:              slug
    with_wildcard_routes: true
      
a_event_admin_removeFilter:
  url:   /admin/aEventAdmin/remove_filter/:name/:value
  param: { module: aEventAdmin, action: removeFilter }
  class: sfRoute
  
a_event_admin_addFilter:
  url:   /admin/aEventAdmin/add_filter/:name/:value
  param: { module: aEventAdmin, action: addFilter }
  class: sfRoute
  
a_event_admin_autocomplete:
  url:   /admin/aEventAdmin/autocomplete
  param: { module: aEventAdmin, action: autocomplete }
  class: sfRoute  
      
a_event_category_admin:
  class: sfDoctrineRouteCollection
  options:
    model:               aEventCategory
    module:              aEventCategoryAdmin
    prefix_path:         admin/event_categories
    column:              id
    with_wildcard_routes: true
    collection_actions:
      addFilter: [GET, POST]
      removeFilter: [GET, POST]