a_blog:
  url:
  param: { module: aBlog, action: index }
  class: aRoute

a_blog_post:
  url:      /aBlog/show/:id
  param:    { module: aBlog, action: show }
  options:  { model: aBlogPost, type: object }
  class:    sfDoctrineRoute
  
  
################
# admin routes #
################

a_blog_admin:
  class: sfDoctrineRouteCollection
  options:
    model:               aBlogPost
    module:              aBlogAdmin
    prefix_path:         admin/a_blog_admin
    column:              id
    with_wildcard_routes: true
    collection_actions:
      addFilter: [GET, POST]
      removeFilter: [GET, POST]
      
a_blog_category_admin:
  class: sfDoctrineRouteCollection
  options:
    model:               aBlogCategory
    module:              aBlogCategoryAdmin
    prefix_path:         admin/a_blog_category_admin
    column:              id
    with_wildcard_routes: true
    collection_actions:
      addFilter: [GET, POST]
      removeFilter: [GET, POST]