options:
  type: INNODB

aBlogEngine:
  columns:
    page_id: integer(4)
    options: string
  relations:
    Page:
      class: aPage
      local: page_id
      foreign: id
      onDelete: cascade

aBlogItem:
  actAs:
    Timestampable: ~
    Taggable: ~
    Sluggable: ~
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    author_id:
      type: integer(4)
    body_id:
      type: integer(4)
    title:
      type: string(255)
      notnull: true
    excerpt:
      type: string
    status:
      type: enum
      values: [draft, pending review, published ]
      notnull: true
      default: draft
    public:
      type: boolean
      notnull: true
      default: 0
  relations:
    Author:
      class: sfGuardUser
      foreignAlias: BlogAuthorItems
      local: author_id
      foreign: id
      onDelete: SET NULL
    Editors:
      foreignAlias: BlogEditorItems
      class: sfGuardUser
      refClass: aBlogEditor
      local: blog_item_id
      foreign: user_id
    Body:
      class: aArea
      local: body_id
      foreign: id
      onDelete: CASCADE
    Categories:
      foreignAlias: BlogItems
      class: aBlogCategory
      refClass: aBlogItemCategory
      local: blog_item_id
      foreign: blog_category_id
      
      
aBlogEditor:
  columns:
    blog_item_id: 
      type: integer
      primary: true
    user_id:
      type: integer(4)
      primary: true
  relations:
    BlogItem:
      foreignAlias: BlogItemEditors
      class: aBlogItem
      local: blog_item_id
    Editor:
      foreignAlias: BlogItemEditors
      class: sfGuardUser
      local: user_id
      
aBlogItemCategory:
  columns:
    blog_item_id:
      type: integer
      primary: true
    blog_category_id:
      type: integer
      primary: true
  relations:
    BlogItem:
      foreignAlias: BlogItemCategories
      class: aBlogItem
      local: blog_item_id
    BlogCategory:
      foreignAlias: BlogItemCategories
      class: aBlogCategory
      local: blog_category_id
      
aBlogCategory:
  columns:
    name: string(128)
  relations:
    Users:
      foreignAlias: BlogCategories
      class: sfGuardUser
      refClass: aBlogCategoryUser
      local: blog_category_id
      foreign: user_id
    BlogItems:
      foreignAlias: BlogCategories
      class: aBlogItem
      refClass: aBlogItemCategory
      local: blog_category_id
      foreign: blog_item_id
    
aBlogCategoryUser:
  columns:
    blog_category_id:
      type: integer
      primary: true
    user_id:
      type: integer(4)
      primary: true
  relations:
    BlogCategory:
      foreignAlias: BlogCategoryUsers
      class: aBlogCategory
      local: blog_category_id
    User:
      foreignAlias: BlogCategoryUsers
      class: sfGuardUser
      local: user_id
    
aBlogPost:
  inheritance:
    extends: aBlogItem
    type: column_aggregation
    keyField: type
    keyValue: 'post'
  columns:
    published_at:
      type: timestamp
  relations:
    Author:
      foreignAlias: BlogAuthorPosts
      class: sfGuardUser
      local: author_id
      foreign: id
      onDelete: SET NULL
    Editors:
      foreignAlias: BlogEditorPosts
      class: sfGuardUser
      refClass: aBlogEditor
      local: blog_item_id
      foreign: user_id
    Body:
      class: aArea
      local: body_id
      foreign: id
      onDelete: CASCADE
    Categories:
      foreignAlias: BlogPosts
      class: aBlogCategory
      refClass: aBlogItemCategory
      local: blog_item_id
      foreign: blog_category_id
      