generator:
  class: sfDoctrineGenerator
  param:
    model_class:           aBlogCategory
    theme:                 aBlogAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          a_blog_category_admin
    with_doctrine_route:   1
    
    config:
      
      list:
        title: Categories
        display: [ _name, numBlogPosts, numEvents, _users ]
        object_actions: []
        actions:
          new:
            label: New Post
            action: new
            params:
              class: a-btn big icon a-add alt
          posts:
            label: Posts
            action: posts
            params:
              class: a-btn big alt
          events:
            label: Events
            action: events
            params:
              class: a-btn big alt

      
      form:
        fields:   [ name, users_list, posts, events ]
        display:  [ name, users_list, posts, events ]
        
      filter:
        fields:  [  users_list ]
        display: [  users_list ]
        
      fields:
        numBlogPosts: { label: Number of Posts }
        numEvents: { label: Number of Events }
        users: { label: Active Users }
      
      edit:
        title: Edit Category
        