generator:
  class: sfDoctrineGenerator
  param:
    model_class:           aBlogCategory
    theme:                 aBlogAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          a_blog_category_admin
    with_doctrine_route:   1
    
    config:
      actions: []
    
      list:
        display: [ _name, numBlogItems, numUsers ]
        object_actions: []
        actions:
          _new:
            name: New
        table_method: 
      
      form:
        fields:   [ name, users_list ]
        display:  [ name, users_list ]
        
      filter:
        fields:  [ name, users_list ]
        display: [ name, users_list ]
        
      fields:
        numBlogItems: { label: Blog Items Count }
        numUsers: { label: Active Users }
      
      edit:
        actions: ~
        